apiVersion: apps/v1
kind: Deployment
metadata:
name: server1-deployment
spec:
replicas: 2
selector:
    matchLabels:
    app: server1
template:
    metadata:
    labels:
        app: server1
    spec:
    containers:
    - name: server1
        image: konami98/flask-server-1:v2
        ports:
        - containerPort: 5001
    nodeSelector:
        role: worker-node
---
apiVersion: v1
kind: Service
metadata:
name: server1-service
spec:
selector:
    app: server1
ports:
    - protocol: TCP
    port: 5001
    targetPort: 5001
    nodePort: 30001
type: NodePort
